### ISSUE TITLE
UF2 Tener productos clasificados como deluxe 

### ISSUE THREAD

**Issue by Japoivvb** [Jachias21/M03#2]
añadir atributo deluxe a producto como true para precios publicos de mas de 100€, se ha de mostrar en la opcion 5 de menu

**Comment by Jachias21** [comment]
<img width="1300" alt="Captura de pantalla 2024-06-13 a las 10 57 56" src="https://github.com/Jachias21/M03/assets/167965840/8955c531-1166-44ac-afac-e8d4c7a772e1">
<img width="1202" alt="Captura de pantalla 2024-06-13 a las 10 58 41" src="https://github.com/Jachias21/M03/assets/167965840/a4116444-2ac5-456b-aabf-c64d4d23dd9a">

**Comment by Japoivvb** [comment]
el issue lo cierra la persona que lo abre tras verificacion, reabrelo por favor
